#!/usr/bin/env -S "populate_pre_commit"
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # managed-by-populate-pre-commit start: conventional-pre-commit.yaml
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
    - id: conventional-pre-commit
      stages:
      - commit-msg
      args:
      - --verbose
  # managed-by-populate-pre-commit end: conventional-pre-commit.yaml
  # managed-by-populate-pre-commit start: hooks.yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-illegal-windows-names
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: check-yaml
    - id: destroyed-symlinks
    - id: fix-byte-order-marker
    - id: mixed-line-ending
  # managed-by-populate-pre-commit end: hooks.yaml
  # managed-by-populate-pre-commit start: json.yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-json
      exclude: ^\.vscode/settings\.json|package-lock\.json$
    - id: pretty-format-json
      exclude: ^\.vscode/settings\.json|package-lock\.json$
      args:
      - --autofix
  # managed-by-populate-pre-commit end: json.yaml
  # managed-by-populate-pre-commit start: keep-sorted.yaml
  - repo: https://github.com/google/keep-sorted
    rev: v0.9.0
    hooks:
    - id: keep-sorted
  # managed-by-populate-pre-commit end: keep-sorted.yaml
  # managed-by-populate-pre-commit start: markdownlint.yaml
  - repo: local
    hooks:
    - id: markdownlint
      name: Run `markdownlint`
      language: system
      types:
      - markdown
      exclude: CODE_OF_CONDUCT.md
      entry: markdownlint
  # managed-by-populate-pre-commit end: markdownlint.yaml
  # managed-by-populate-pre-commit start: meta.yaml
  - repo: meta
    hooks:
    - id: check-hooks-apply
  # managed-by-populate-pre-commit end: meta.yaml
  # managed-by-populate-pre-commit start: readme-toc.yaml
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.5.0
    hooks:
    - id: doctoc
      files: README.md
      args:
      - --notitle
      - --minlevel=2
      - --mintocitems=3
      - --github
  # managed-by-populate-pre-commit end: readme-toc.yaml
  # managed-by-populate-pre-commit start: shellcheck.yaml
  - repo: local
    hooks:
    - id: shellcheck
      name: Run `shellcheck`
      language: system
      types:
      - shell
      entry: shellcheck -e SC1090 -e SC1091
  # managed-by-populate-pre-commit end: shellcheck.yaml
  # managed-by-populate-pre-commit start: spellcheck.yaml
  - repo: local
    hooks:
    - id: spellcheck
      stages:
      - commit-msg
      name: Check spelling
      language: system
      verbose: true
      entry: spell-check-wrapper
  # managed-by-populate-pre-commit end: spellcheck.yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: phpinsights
        name: Run `phpinsights`
        language: script
        pass_filenames: false
        types: [php]
        entry: phpinsights-pre-commit --quiet
      - id: phplint
        name: Run `php -l`
        language: script
        types: [php]
        entry: php-l-pre-commit
      - id: phpstan
        name: Run `phpstan`
        language: system
        pass_filenames: false
        types: [php]
        entry: run-if-exists phpstan analyse --memory-limit=1G
      - id: phpunit
        name: Run `phpunit`
        language: script
        types: [php]
        pass_filenames: false
        entry: phpunit-pre-commit
