#!/bin/bash

set -e -f -u -o pipefail

# Ensure the two configs are in sync.
diff -u check_website_resources-dev.json \
  <(sed -e 's/www.arianetobin.ie/dev.arianetobin.ie/' \
      check_website_resources.json)
set +f
check_website_resources -- *.json
