#!/bin/bash

set -e -f -u -o pipefail

files_being_committed_includes() {
  git diff --cached --name-only --diff-filter=ACM \
    | (grep "$@" || true)
}

if [[ -n "$(files_being_committed_includes '.php$')" ]]; then
  # "PHPUnit 7.5.6 by Sebastian Bergmann and contributors." -> 7
  version="$(phpunit --version | awk '{sub("\\..*", "", $2); print $2}')"
  if [[ "${version}" -ge 9 ]]; then
    # PHPUnit isn't backwards-compatible so I can't run the tests on earlier
    # versions :(
    phpunit --no-coverage
  fi
fi

if [[ -n "$(files_being_committed_includes '.json$')" ]]; then
  # Ensure the two configs are in sync.
  diff -u check_website_resources-dev.json \
    <(sed -e 's/www.arianetobin.ie/dev.arianetobin.ie/' \
        check_website_resources.json)
  check_website_resources -- *.json
fi
