#!/bin/bash

set -e -f -u -o pipefail

php_files_being_committed() {
  git diff --cached --name-only --diff-filter=ACM \
    | (grep '.php$' || true)
}

if [[ -n "$(php_files_being_committed)" ]]; then
  # "PHPUnit 7.5.6 by Sebastian Bergmann and contributors." -> 7
  version="$(phpunit --version | awk '{sub("\\..*", "", $2); print $2}')"
  if [[ "${version}" -ge 9 ]]; then
    # PHPUnit isn't backwards-compatible so I can't run the tests on earlier
    # versions :(
    phpunit --no-coverage
  fi
fi

# Ensure the two configs are in sync.
diff -u check_website_resources-dev.json \
  <(sed -e 's/www.arianetobin.ie/dev.arianetobin.ie/' \
      check_website_resources.json)
