#!/bin/bash

set -e -f -u -o pipefail

MODULES_DIR="../phplint-modules"
FAKE_WORDPRESS="FakeWordpress.php"
if [[ ! -f "${FAKE_WORDPRESS}" ]]; then
  printf "%s: Missing %s; are you running from src/?\\n" \
    "$0" "${FAKE_WORDPRESS}" >&2
  exit 1
fi
if [[ "$#" -eq 0 ]]; then
  printf "%s: need at least one argument for phpl (usually filename.php)\\n" \
    "$0" >&2
  exit 1
fi

set +f
rm "${MODULES_DIR}"/*
ln -s /usr/local/Cellar/phplint/*/libexec/modules/*.php "${MODULES_DIR}"
set -f

ln -s "${PWD}/FakeCart66.php" "${MODULES_DIR}/fakecart66.php"

(printf "<?php\\n";
 sed -n \
   -e '/phplint.*function/ s/.*phplint: //p' \
   -e '/BEGIN PHPLINT/,/END PHPLINT/ p' \
   "${FAKE_WORDPRESS}";
 printf "?>\\n"
) > "${MODULES_DIR}/wordpress.php"

phpl --modules-path "${MODULES_DIR}" --print-file-name --print-line-numbers \
  --no-ascii-ext-check "$@"
